#! /bin/bash
NAME="marvelapi"
DJANGODIR="/opt/marvelapi/"
SOCKFILE="/opt/marvelapi/run/gunicorn.sock"
USER="django"
GROUP="webapps"
NUM_WORKERS="3"
DJANGO_SETTINGS_MODULE=marvelapi.settings
DJANGO_WSGI_MODULE=marvelapi.wsgi
VIRTUALENV="/opt/.env/bin/activate"

echo "Starting $NAME as whoami"

cd $DJANGODIR
source $VIRTUALENV
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$FJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec /opt/.env/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE  \
  --log-level=debug \
  --log-file=-
